 grades <- read.csv('\\Users\\vid82\\OneDrive\\Documents\\CS\\CS237\\grades.csv')

View(grades)
summary(grades)
sd(grades$class1)
sd(grades$class2)
sd(grades$class3)
boxplot(grades)
table(grades$class1)
table(grades$class2)
table(grades$class3)
pmf1 <- table(grades$class1)
pmf2 <- table(grades$class2)
pmf3 <- table(grades$class3)
plot(pmf1/57)
plot(pmf2/57)
plot(pmf3/57)
